"""categories add organization_id

Revision ID: 2f9cd5933862
Revises: e8b97310cb44
Create Date: 2025-07-25 16:50:27.550129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9cd5933862'
down_revision: Union[str, None] = 'e8b97310cb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'categories', 'organizations', ['organization_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'organization_id')
    # ### end Alembic commands ###
