"""scope cleanup

Revision ID: 4af5a3d4b4b5
Revises: a64fbca2ceff
Create Date: 2025-05-31 16:51:33.675693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af5a3d4b4b5'
down_revision: Union[str, None] = 'a64fbca2ceff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expenses_scope_id_fkey', 'expenses', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('expenses_scope_id_fkey', 'expenses', 'scopes', ['scope_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###
