"""Import Job table

Revision ID: 594baf6fa50f
Revises: 727702100769
Create Date: 2025-06-10 23:17:44.363058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594baf6fa50f'
down_revision: Union[str, None] = '727702100769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='import_job_status'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_import_jobs_uuid'), 'import_jobs', ['uuid'], unique=False)
    op.add_column('expenses', sa.Column('import_job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'import_jobs', ['import_job_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'import_job_id')
    op.drop_index(op.f('ix_import_jobs_uuid'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
