"""rename expense table to transaction

Revision ID: 5a9c5a942593
Revises: b651088c14cf
Create Date: 2025-06-29 14:02:55.211997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a9c5a942593'
down_revision: Union[str, None] = 'b651088c14cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.uuid'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.uuid'], ),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.uuid'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_transactions_uuid'), 'transactions', ['uuid'], unique=False)
    op.drop_index('ix_expenses_uuid', table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('import_job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fingerprint', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.uuid'], name='expenses_account_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.uuid'], name='expenses_category_id_fkey'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.uuid'], name='expenses_import_job_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.uuid'], name='expenses_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.uuid'], name='expenses_user_id_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='expenses_pkey')
    )
    op.create_index('ix_expenses_uuid', 'expenses', ['uuid'], unique=False)
    op.drop_index(op.f('ix_transactions_uuid'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
