"""Expense account_id

Revision ID: 727702100769
Revises: 78722e644f8b
Create Date: 2025-06-10 22:58:00.638152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727702100769'
down_revision: Union[str, None] = '78722e644f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('account_id', sa.UUID(), nullable=True))
    op.drop_column('expenses', 'scope_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('scope_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('expenses', 'account_id')
    # ### end Alembic commands ###
