"""Transactions add subscription_candidate

Revision ID: 82c74ed5c377
Revises: ea157a18309c
Create Date: 2026-02-08 21:38:58.999556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c74ed5c377'
down_revision: Union[str, None] = 'ea157a18309c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('subscription_candidate', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'subscription_candidate')
    # ### end Alembic commands ###
