"""category enum to str

Revision ID: 84c1022da4e1
Revises: 78cd81e70acd
Create Date: 2025-06-10 22:32:23.095429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84c1022da4e1'
down_revision: Union[str, None] = '78cd81e70acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=postgresql.ENUM('INCOME', 'SUBSCRIPTIONS_AND_MEMBERSHIPS', 'VARIABLE_EXPENSES', 'SAVINGS_AND_INVESTMENTS', 'DEBT_PAYMENTS', 'FIXED_EXPENSES', 'DISCRETIONARY_EXPENSES', 'MISCELLANEOUS', name='category_type'),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('INCOME', 'SUBSCRIPTIONS_AND_MEMBERSHIPS', 'VARIABLE_EXPENSES', 'SAVINGS_AND_INVESTMENTS', 'DEBT_PAYMENTS', 'FIXED_EXPENSES', 'DISCRETIONARY_EXPENSES', 'MISCELLANEOUS', name='category_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
