"""classes cleanup

Revision ID: 94ea7ea34442
Revises: 594baf6fa50f
Create Date: 2025-06-10 23:36:45.592350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ea7ea34442'
down_revision: Union[str, None] = '594baf6fa50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('import_job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'import_jobs', ['import_job_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'import_job_id')
    # ### end Alembic commands ###
