"""project start_date and end_date

Revision ID: 98f78da15eb8
Revises: 6ebcaf4ef844
Create Date: 2025-02-01 08:33:45.137227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f78da15eb8'
down_revision: Union[str, None] = '6ebcaf4ef844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###
