"""cascade scope_id

Revision ID: 9ca8158e36fb
Revises: a2bf6d3165c7
Create Date: 2025-04-12 22:00:42.447604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca8158e36fb'
down_revision: Union[str, None] = 'a2bf6d3165c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expenses_scope_id_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'scopes', ['scope_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_scope_id_fkey', 'expenses', 'scopes', ['scope_id'], ['uuid'])
    # ### end Alembic commands ###
