"""project_id

Revision ID: a2bf6d3165c7
Revises: 6c8d2562538b
Create Date: 2025-04-12 21:54:41.928925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2bf6d3165c7'
down_revision: Union[str, None] = '6c8d2562538b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scopes_project_id_fkey', 'scopes', type_='foreignkey')
    op.create_foreign_key(None, 'scopes', 'projects', ['project_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scopes', type_='foreignkey')
    op.create_foreign_key('scopes_project_id_fkey', 'scopes', 'projects', ['project_id'], ['uuid'])
    # ### end Alembic commands ###
