"""Project changes

Revision ID: a64fbca2ceff
Revises: 9ca8158e36fb
Create Date: 2025-04-28 15:13:40.870736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64fbca2ceff'
down_revision: Union[str, None] = '9ca8158e36fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'projects', ['project_id'], ['uuid'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'projects', ['parent_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'parent_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'project_id')
    # ### end Alembic commands ###
