"""import job new file properties

Revision ID: a91c816cb59c
Revises: fb5f09109602
Create Date: 2025-06-26 19:41:28.000864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91c816cb59c'
down_revision: Union[str, None] = 'fb5f09109602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'expenses', 'accounts', ['account_id'], ['uuid'])
    op.add_column('import_jobs', sa.Column('file_url', sa.String(length=255), nullable=True))
    op.add_column('import_jobs', sa.Column('file_type', sa.String(length=32), nullable=False))
    op.add_column('import_jobs', sa.Column('file_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'file_size')
    op.drop_column('import_jobs', 'file_type')
    op.drop_column('import_jobs', 'file_url')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    # ### end Alembic commands ###
