"""account file key

Revision ID: a98ec0cf6ef1
Revises: 577be644c4ff
Create Date: 2025-08-13 14:24:16.276661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98ec0cf6ef1'
down_revision: Union[str, None] = '577be644c4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('file_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'file_key')
    # ### end Alembic commands ###
