"""timezone

Revision ID: b1ca743d21d4
Revises: 9edcdf10993a
Create Date: 2026-07-18 09:17:36.157741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ca743d21d4'
down_revision: Union[str, None] = '9edcdf10993a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.drop_index('ix_transactions_subscription_id', table_name='transactions')
    op.add_column('user_table', sa.Column('timezone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'timezone')
    op.create_index('ix_transactions_subscription_id', 'transactions', ['subscription_id'], unique=False)
    op.drop_column('organizations', 'timezone')
    # ### end Alembic commands ###
