"""account remove import_job_id

Revision ID: b651088c14cf
Revises: a91c816cb59c
Create Date: 2025-06-26 22:21:56.530389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b651088c14cf'
down_revision: Union[str, None] = 'a91c816cb59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_import_job_id_fkey', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'import_job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('import_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('accounts_import_job_id_fkey', 'accounts', 'import_jobs', ['import_job_id'], ['uuid'])
    # ### end Alembic commands ###
