"""project table total_cost, budget and descriptiom

Revision ID: d33e801d6ef1
Revises: 4af5a3d4b4b5
Create Date: 2025-05-31 16:57:38.164592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33e801d6ef1'
down_revision: Union[str, None] = '4af5a3d4b4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('budget', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
