"""type column to transactions table

Revision ID: e8b97310cb44
Revises: 5a9c5a942593
Create Date: 2025-07-03 18:22:20.347124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b97310cb44'
down_revision: Union[str, None] = '5a9c5a942593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###
