"""categories table slug row

Revision ID: ea157a18309c
Revises: a98ec0cf6ef1
Create Date: 2025-09-23 15:53:18.047695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea157a18309c'
down_revision: Union[str, None] = 'a98ec0cf6ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
