"""Add fingerprint to Expense table'

Revision ID: fb5f09109602
Revises: 94ea7ea34442
Create Date: 2025-06-10 23:48:54.483988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5f09109602'
down_revision: Union[str, None] = '94ea7ea34442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('fingerprint', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'fingerprint')
    # ### end Alembic commands ###
